spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/h2/schema
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      # format_sql: true
logging.level:
  org.hibernate.SQL: debug
